### ISSUE TITLE
ログアウト不可

### ISSUE THREAD

**Issue by jin-kazama-mt** [Yuta-Fukui/next-hobby#1]
ログアウトをしようとすると以下のようなエラーが表示される

Unhandled Runtime Error
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

Source
src\utils\dashboard\header.hooks.ts (4:27) @ useRouter

  2 |
  3 | export default function HeaderHooks() {
> 4 |   const router = useRouter();
    |                           ^
  5 |   const logout = async () => {
  6 |     await fetch("/api/session", {
  7 |       method: "DELETE",

Call Stack
Show collapsed frames

**Comment by Yuta-Fukui** [comment]
こちら対応しました
https://github.com/Yuta-Fukui/next-hobby/commit/7ad83e29cf2cd32fdddf424ad38bd1b67c0a58ff
